baseURL = 'https://blogdarkspot.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

[[menu.main]]
    name = 'Posts'
    url = '/posts'
    weight = 2

[[menu.main]]
    name = 'Resume'
    url = '/cv'
    weight = 3

[[menu.main]]
    name = 'About'
    url = '/about'
    weight = 4

